name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Change if your default branch is 'master'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SECRET_NAME: GCP_SA_KEY

jobs:
  build-and-deploy:
    name: Build and Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # ✅ Proper authentication using google-github-actions/auth
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # ✅ Setup gcloud CLI with the authenticated credentials
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Ensure Secret Exists in Secret Manager
      run: |
        if ! gcloud secrets describe $SECRET_NAME --project=$PROJECT_ID; then
          gcloud secrets create $SECRET_NAME --replication-policy=automatic --project=$PROJECT_ID
        fi

    - name: Authenticate with Google Cloud using GitHub Secret
      run: |
        echo "${{ secrets.GCP_SA_KEY_JSON }}" > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}


    # ✅ Authenticate Docker with Artifact Registry
    - name: Authenticate Docker to Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

    # 🛠️ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO }}/${{ secrets.IMAGE_NAME }} .

    # 🚀 Push Docker image to Artifact Registry
    - name: Push Docker image
      run: |
        docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO }}/${{ secrets.IMAGE_NAME }}

    # 📦 Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.SERVICE_NAME }} \
          --image ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO }}/${{ secrets.IMAGE_NAME }} \
          --region ${{ secrets.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets=GCP_SA_KEY=GCP_SA_KEY:latest \
          --set-env-vars "GCP_BUCKET_NAME=${{secrets.GCP_BUCKET_NAME}},STABILITY_API_KEY=${{ secrets.STABILITY_API_KEY }}" \
          --timeout=900s